import os
import sys
import django
import json
import requests
from datetime import timedelta

# Setup Django Environment
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'core.settings')
django.setup()

from employees.models import Department, Designation, Employee
from authentication.models import UserCredentials
from permissions.models import ServiceAccess, HdmsRole

BASE_URL = "http://localhost:8000/api"

def print_step(msg):
    print(f"\n{'='*50}\n>> {msg}\n{'='*50}")

def print_success(msg):
    print(f"[OK] SUCCESS: {msg}")

def print_fail(msg):
    print(f"[X] FAILED: {msg}")

def run_test():
    print_step("STEP 1: Creating Test Data")
    
    # 1. Create Department
    dept, _ = Department.objects.get_or_create(
        dept_name="Test Dept",
        defaults={
            "dept_code": "TEST",
            "dept_sector": "it",
            "description": "For automated testing"
        }
    )
    print(f"Created Department: {dept.dept_name} ({dept.department_id})")

    # 2. Create Designation
    desig, _ = Designation.objects.get_or_create(
        position_code="TEST-01",
        department=dept,
        defaults={
            "position_name": "Test Engineer"
        }
    )
    print(f"Created Designation: {desig.position_name}")

    # 3. Create Employee
    emp, created = Employee.objects.get_or_create(
        cnic="11111-1111111-1",
        defaults={
            "full_name": "Test User",
            "phone": "0300-0000000",
            "email": "test@example.com",
            "department": dept,
            "designation": desig,
            "gender": "male",
            "dob": "1990-01-01",
            "joining_date": "2024-01-01"
        }
    )
    if created:
        # Force save to generate IDs if not generated by get_or_create signals
        emp.save()
    print(f"Created Employee: {emp.full_name} ({emp.employee_code})")

    # 4. Create Credentials
    UserCredentials.objects.filter(employee=emp).delete() # Reset
    ServiceAccess.objects.filter(employee=emp).delete()   # Reset permissions
    creds = UserCredentials.objects.create(employee=emp)
    creds.set_password("password123")
    creds.save()
    print("Created Password: password123")

    # ==========================================
    
    print_step("STEP 2: Testing Login API")
    
    login_url = f"{BASE_URL}/auth/login"
    payload = {
        "employee_code": emp.employee_code,
        "password": "password123"
    }
    
    try:
        response = requests.post(login_url, json=payload)
        if response.status_code == 200:
            data = response.json()
            token = data['access_token']
            print_success("Login Successful!")
            print(f"Token received: {token[:20]}...")
        else:
            print_fail(f"Login failed: {response.text}")
            return
    except Exception as e:
        print_fail(f"Could not connect to API: {e}")
        return

    headers = {"Authorization": f"Bearer {token}"}

    # ==========================================

    print_step("STEP 3: Testing Default Permissions (Should Fail)")
    
    # Check SIS Access
    check_url = f"{BASE_URL}/permissions/check/sis"
    resp = requests.get(check_url, headers=headers)
    
    try:
        data = resp.json()
        if data['has_access'] == False:
            print_success("Correctly denied SIS access (Default)")
        else:
            print_fail("Unexpectedly granted SIS access!")
    except:
        print_fail(f"API Error (Status {resp.status_code}): {resp.text}")
        return

    # ==========================================

    print_step("STEP 4: Granting Permissions via Backend")
    
    # Grant SIS Access
    ServiceAccess.objects.get_or_create(
        employee=emp,
        service='sis',
        defaults={'is_active': True}
    )
    print("Granted SIS Access to Test User")

    # Grant HDMS Access + Role
    sa_hdms, _ = ServiceAccess.objects.get_or_create(
        employee=emp,
        service='hdms',
        defaults={'is_active': True}
    )
    HdmsRole.objects.get_or_create(
        service_access=sa_hdms,
        defaults={'role_type': 'moderator'}
    )
    print("Granted HDMS Access + Moderator Role")

    # ==========================================

    print_step("STEP 5: Re-Testing Permissions (Should Succeed)")

    # Check SIS Access
    resp = requests.get(f"{BASE_URL}/permissions/check/sis", headers=headers)
    data = resp.json()
    if data['has_access'] == True:
        print_success("SIS Access Verified!")
        print(f"Role Info: {data.get('role_info')}")
    else:
        print_fail("SIS Access still denied!")

    # Check HDMS Access
    resp = requests.get(f"{BASE_URL}/permissions/check/hdms", headers=headers)
    data = resp.json()
    if data['has_access'] == True:
        print_success("HDMS Access Verified!")
        print(f"Role Info: {data.get('role_info')}")
    else:
        print_fail("HDMS Access still denied!")

    print_step("TEST COMPLETE")

if __name__ == "__main__":
    run_test()
