# Generated by Django 5.0.1 on 2025-12-02 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, help_text='Bank account number', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name for salary account', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, help_text='City of residence', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='education_history',
            field=models.JSONField(blank=True, help_text='Array of education records: [{degree, institute, passingYear}]', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, help_text='Emergency contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', help_text='Type of employment', max_length=20),
        ),
        migrations.AddField(
            model_name='employee',
            name='nationality',
            field=models.CharField(blank=True, default='Pakistani', help_text="Employee's nationality", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization_phone',
            field=models.CharField(blank=True, help_text='Phone number provided by organization', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, help_text='Permanent home address', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, help_text="Employee's religion (optional)", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='residential_address',
            field=models.TextField(blank=True, help_text='Current residential address', null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='resume',
            field=models.FileField(blank=True, help_text='Employee resume/CV file', null=True, upload_to='resumes/%Y/%m/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, help_text='State/Province', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='work_experience',
            field=models.JSONField(blank=True, help_text='Array of experience records: [{employer, jobTitle, startDate, endDate, responsibilities}]', null=True),
        ),
    ]
