# Generated by Django 4.2 on 2026-01-06 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employeeassignment_institution_organization_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='email',
            new_name='personal_email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
        migrations.AddField(
            model_name='employee',
            name='org_email',
            field=models.EmailField(blank=True, help_text='Official Organization Email', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='org_phone',
            field=models.CharField(blank=True, help_text='Official Mobile/Extension', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='personal_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
