# Generated by Django 5.0.1 on 2025-11-29 07:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlacklistedToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='JWT access token', max_length=500, unique=True)),
                ('blacklisted_at', models.DateTimeField(auto_now_add=True, help_text='When token was blacklisted')),
                ('expires_at', models.DateTimeField(help_text='When token naturally expires (can be cleaned up after)')),
                ('reason', models.CharField(default='logout', help_text='Reason for blacklisting (logout, security, etc.)', max_length=100)),
            ],
            options={
                'verbose_name': 'Blacklisted Token',
                'verbose_name_plural': 'Blacklisted Tokens',
                'db_table': 'auth_blacklisted_token',
                'indexes': [models.Index(fields=['token'], name='auth_blackl_token_e0c274_idx'), models.Index(fields=['expires_at'], name='auth_blackl_expires_b577d7_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserCredentials',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('password_hash', models.CharField(help_text='Hashed password', max_length=255)),
                ('last_login', models.DateTimeField(blank=True, help_text='Last login timestamp', null=True)),
                ('last_login_ip', models.GenericIPAddressField(blank=True, help_text='IP address of last login', null=True)),
                ('password_changed_at', models.DateTimeField(default=django.utils.timezone.now, help_text='When password was last changed')),
                ('failed_login_attempts', models.IntegerField(default=0, help_text='Count of consecutive failed login attempts')),
                ('locked_until', models.DateTimeField(blank=True, help_text='Account locked until this time (after too many failed attempts)', null=True)),
                ('employee', models.OneToOneField(help_text='Employee these credentials belong to', on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='employees.employee')),
            ],
            options={
                'verbose_name': 'User Credentials',
                'verbose_name_plural': 'User Credentials',
                'db_table': 'auth_user_credentials',
            },
        ),
        migrations.CreateModel(
            name='RefreshToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(help_text='JWT refresh token', max_length=500, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When token was created')),
                ('expires_at', models.DateTimeField(help_text='When token expires')),
                ('is_revoked', models.BooleanField(default=False, help_text='Has this token been revoked?')),
                ('device_info', models.CharField(blank=True, help_text='Device/browser info (User-Agent)', max_length=255, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address where token was created', null=True)),
                ('employee', models.ForeignKey(help_text='Employee this token belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Refresh Token',
                'verbose_name_plural': 'Refresh Tokens',
                'db_table': 'auth_refresh_token',
                'indexes': [models.Index(fields=['token'], name='auth_refres_token_09c3b2_idx'), models.Index(fields=['employee', 'is_revoked'], name='auth_refres_employe_6d482e_idx'), models.Index(fields=['expires_at'], name='auth_refres_expires_6976f5_idx')],
            },
        ),
    ]
