# Generated by Django 4.2 on 2026-01-27 11:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_employment_type'),
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercredentials',
            name='employee',
            field=models.OneToOneField(blank=True, help_text='Employee these credentials belong to (if employee)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='employees.employee'),
        ),
        migrations.CreateModel(
            name='SuperAdmin',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('superadmin_code', models.CharField(help_text='Superadmin code in format S-YY-NNNN (e.g., S-25-0001)', max_length=20, unique=True)),
                ('full_name', models.CharField(help_text='Full name of the superadmin', max_length=255)),
                ('email', models.EmailField(help_text='Official email address', max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this superadmin account active?')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(blank=True, help_text='Primary organization (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='superadmins', to='employees.organization')),
            ],
            options={
                'verbose_name': 'Super Administrator',
                'verbose_name_plural': 'Super Administrators',
                'db_table': 'auth_superadmin',
                'ordering': ['superadmin_code'],
            },
        ),
        migrations.AddField(
            model_name='usercredentials',
            name='superadmin',
            field=models.OneToOneField(blank=True, help_text='SuperAdmin these credentials belong to (if superadmin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='authentication.superadmin'),
        ),
    ]
