# Generated by Django 5.0.1 on 2026-04-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_refreshtoken_superadmin_alter_refreshtoken_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refreshtoken',
            name='token',
            field=models.TextField(help_text='JWT token (RS256 tokens are ~700+ chars, TextField avoids length limit)', unique=True),
        ),
    ]
