# Generated by Django 5.0.1 on 2025-12-01 10:26

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('object_id', models.CharField(help_text='ID of the object that was changed', max_length=255)),
                ('action', models.CharField(choices=[('create', 'Created'), ('update', 'Updated'), ('delete', 'Deleted'), ('restore', 'Restored')], help_text='Type of action performed', max_length=10)),
                ('field_name', models.CharField(blank=True, help_text='Field that was changed (for updates)', max_length=100, null=True)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (for updates)', null=True)),
                ('new_value', models.TextField(blank=True, help_text='New value (for updates)', null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='When the change occurred')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of the user', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional context or reason for change', null=True)),
                ('changed_by', models.ForeignKey(blank=True, help_text='Employee who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='employees.employee')),
                ('content_type', models.ForeignKey(help_text='Type of object that was changed', on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='audit_audit_content_4c2ead_idx'), models.Index(fields=['changed_by', '-timestamp'], name='audit_audit_changed_3917fa_idx'), models.Index(fields=['action', '-timestamp'], name='audit_audit_action_e33994_idx')],
            },
        ),
    ]
