# Generated by Django 4.2 on 2026-01-27 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usercredentials_employee_superadmin_and_more'),
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='changed_by_superadmin',
            field=models.ForeignKey(blank=True, help_text='SuperAdmin who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='authentication.superadmin'),
        ),
    ]
