# Generated by Django 5.0.1 on 2025-11-29 06:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_id', models.CharField(blank=True, editable=False, help_text='Auto-generated department ID (e.g., IAK-D-001)', max_length=20, unique=True)),
                ('dept_code', models.CharField(help_text='Department code used in employee_code (e.g., C06-M, AIT01, FIN)', max_length=20, unique=True)),
                ('dept_name', models.CharField(help_text='Full department name', max_length=200)),
                ('dept_sector', models.CharField(choices=[('academic', 'Academic (Schools/Campuses)'), ('it', 'Information Technology'), ('finance', 'Finance & Accounting'), ('medical', 'Medical & Health'), ('hr', 'Human Resources'), ('administration', 'Administration'), ('procurement', 'Procurement'), ('other', 'Other')], default='other', help_text='Organization sector this department belongs to', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Additional details about department', null=True)),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['department_id'],
            },
        ),
        migrations.CreateModel(
            name='AcademicInstitutionInformation',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('address', models.TextField(blank=True, help_text='Physical address of institution', null=True)),
                ('principal_name', models.CharField(blank=True, help_text="Current principal's name", max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, help_text='Institution contact number', max_length=20, null=True)),
                ('student_capacity', models.IntegerField(blank=True, help_text='Total student capacity', null=True)),
                ('established_year', models.IntegerField(blank=True, help_text='Year institution was established', null=True)),
                ('department', models.OneToOneField(help_text='Academic department this info belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='academic_info', to='employees.department')),
            ],
            options={
                'verbose_name': 'Academic Institution Information',
                'verbose_name_plural': 'Academic Institution Information',
            },
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position_code', models.CharField(help_text='Position code used in employee_code (e.g., T, P, DEV, ACC)', max_length=10)),
                ('position_name', models.CharField(help_text='Full position name (e.g., Teacher, Developer)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Role description and responsibilities', null=True)),
                ('department', models.ForeignKey(help_text='Department this designation belongs to (REQUIRED)', on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='employees.department')),
            ],
            options={
                'verbose_name': 'Designation',
                'verbose_name_plural': 'Designations',
                'ordering': ['department__dept_code', 'position_name'],
                'unique_together': {('department', 'position_code')},
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Internal UUID for database relations', primary_key=True, serialize=False)),
                ('employee_id', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated simple ID (e.g., IAK-0001)', max_length=20, unique=True)),
                ('employee_code', models.CharField(blank=True, db_index=True, editable=False, help_text='Auto-generated detailed code (e.g., C06-M-24-T-0001)', max_length=50, unique=True)),
                ('full_name', models.CharField(help_text="Employee's full name", max_length=200)),
                ('cnic', models.CharField(help_text='National ID card number (CNIC)', max_length=15)),
                ('phone', models.CharField(help_text='Contact phone number', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Email address (optional)', max_length=254, null=True)),
                ('dob', models.DateField(help_text='Date of birth')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], help_text='Gender', max_length=10)),
                ('joining_date', models.DateField(help_text='Date employee joined organization')),
                ('is_active', models.BooleanField(default=True, help_text='Can this employee access services?')),
                ('is_superadmin', models.BooleanField(default=False, help_text='Has access to all services and full permissions')),
                ('department', models.ForeignKey(help_text='Department employee belongs to', on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.department')),
                ('designation', models.ForeignKey(help_text="Employee's position (filtered by department)", on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.designation')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['employee_id'], name='employees_e_employe_514cc5_idx'), models.Index(fields=['employee_code'], name='employees_e_employe_f8cfea_idx'), models.Index(fields=['cnic'], name='employees_e_cnic_c856de_idx'), models.Index(fields=['is_active'], name='employees_e_is_acti_ff761b_idx'), models.Index(fields=['is_deleted'], name='employees_e_is_dele_b9e897_idx')],
            },
        ),
    ]
