# Generated by Django 5.0.1 on 2025-12-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_employee_account_number_employee_bank_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dept_code',
            field=models.CharField(help_text='Department code used in employee_code (e.g., C06-M, AIT01, FIN)', max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='position_code',
            field=models.CharField(help_text='Position code used in employee_code (e.g., T, P, DEV, ACC)', max_length=4),
        ),
    ]
