# Generated by Django 4.2 on 2026-01-06 10:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_dept_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeAssignment',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joining_date', models.DateField()),
                ('is_primary', models.BooleanField(default=True, help_text='Determines the central Employee Code')),
                ('is_active', models.BooleanField(default=True)),
                ('shift', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('general', 'General/Office'), ('hourly', 'Hourly Base')], default='general', max_length=20)),
                ('role_data', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Employee Assignment',
                'verbose_name_plural': 'Employee Assignments',
            },
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('inst_id', models.CharField(editable=False, help_text='Auto-generated serial ID', max_length=50, unique=True)),
                ('inst_code', models.CharField(help_text='Unique code (e.g., AIT01, AMC01)', max_length=20, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('inst_type', models.CharField(choices=[('educational', 'Educational (School, College, University)'), ('healthcare', 'Healthcare (Hospital, Clinic, Lab)'), ('social_welfare', 'Social Welfare (Kitchen, Shelter, Center)'), ('administrative', 'Administrative (Office, branch)'), ('technical', 'Technical / Vocational'), ('operational', 'Operational / Project Site'), ('other', 'Other')], max_length=30)),
                ('legacy_campus_id', models.UUIDField(blank=True, help_text='Link to existing SIS Campus UUID', null=True)),
                ('attribute_schema', models.JSONField(blank=True, default=list, help_text='JSON schema for institution-specific attributes')),
                ('extra_data', models.JSONField(blank=True, default=dict)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'verbose_name': 'Institution',
                'verbose_name_plural': 'Institutions',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Organization Name (e.g., Al-Khidmat Foundation)', max_length=255)),
                ('org_code', models.CharField(help_text='Short code for the organization (e.g., AKF)', max_length=10, unique=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('address', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
            },
        ),
        migrations.RemoveField(
            model_name='academicinstitutioninformation',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.AlterModelOptions(
            name='designation',
            options={'verbose_name': 'Designation', 'verbose_name_plural': 'Designations'},
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_employe_514cc5_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_employe_f8cfea_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_cnic_c856de_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_is_acti_ff761b_idx',
        ),
        migrations.RemoveIndex(
            model_name='employee',
            name='employees_e_is_dele_b9e897_idx',
        ),
        migrations.RemoveField(
            model_name='designation',
            name='description',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='department',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='designation',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='employment_type',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='joining_date',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='organization_phone',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='resume',
        ),
        migrations.AddField(
            model_name='designation',
            name='attribute_schema',
            field=models.JSONField(blank=True, default=list, help_text='JSON schema for designation-specific attributes (Google Form style)'),
        ),
        migrations.AddField(
            model_name='employee',
            name='emergency_contact_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_code',
            field=models.CharField(help_text='e.g., HR, FIN, ACAD', max_length=10),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='designation',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='designations', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='designation',
            name='position_code',
            field=models.CharField(help_text='Short code for ID generation (e.g., T, D, M)', max_length=10),
        ),
        migrations.AlterField(
            model_name='designation',
            name='position_name',
            field=models.CharField(help_text='e.g., Teacher, Surgeon, Manager', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bank_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='cnic',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='employee',
            name='education_history',
            field=models.JSONField(blank=True, default=list, help_text='[{degree, institute, passingYear, grade}]'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='emergency_contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_code',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Generated from Primary Assignment', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employee_id',
            field=models.CharField(blank=True, db_index=True, editable=False, help_text='Central Organization ID', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='full_name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10),
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='nationality',
            field=models.CharField(default='Pakistani', max_length=100),
        ),
        migrations.AlterField(
            model_name='employee',
            name='permanent_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='employee',
            name='religion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='work_experience',
            field=models.JSONField(blank=True, default=list, help_text='[{employer, jobTitle, startDate, endDate, responsibilities}]'),
        ),
        migrations.DeleteModel(
            name='AcademicInstitutionInformation',
        ),
        migrations.AddField(
            model_name='institution',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='employees.organization'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.department'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='employees.designation'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.employee'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='local_departments', to='employees.institution'),
        ),
        migrations.AddField(
            model_name='department',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='global_departments', to='employees.organization'),
        ),
        migrations.AddField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='employees.organization'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('institution', 'dept_code'), ('organization', 'dept_code')},
        ),
        migrations.AlterUniqueTogether(
            name='employeeassignment',
            unique_together={('employee', 'department', 'designation')},
        ),
        migrations.RemoveField(
            model_name='department',
            name='department_id',
        ),
        migrations.RemoveField(
            model_name='department',
            name='dept_sector',
        ),
    ]
