# Generated by Django 5.0.1 on 2026-01-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0006_employee_resume_url_alter_employee_personal_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_superadmin',
            field=models.BooleanField(default=False),
        ),
    ]
