# Generated by Django 4.2 on 2026-01-21 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0007_employee_is_superadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('branch_id', models.CharField(editable=False, help_text='Auto-generated: BRANCH-001, BRANCH-002, etc.', max_length=50, unique=True)),
                ('branch_code', models.CharField(help_text='Unique code for employee code generation (e.g., C01, C02, H01)', max_length=20, unique=True)),
                ('branch_name', models.CharField(max_length=255)),
                ('address', models.TextField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('district', models.CharField(blank=True, max_length=100, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=20, null=True)),
                ('secondary_contact', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('branch_head_name', models.CharField(blank=True, max_length=255, null=True)),
                ('branch_head_contact', models.CharField(blank=True, max_length=50, null=True)),
                ('branch_head_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year this branch was established (common field)', null=True)),
                ('registration_number', models.CharField(blank=True, help_text='Official registration/license number', max_length=100, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('closed', 'Closed'), ('under_construction', 'Under Construction')], default='active', max_length=20)),
                ('domain_data', models.JSONField(blank=True, default=dict, help_text='\n        Domain-specific attributes stored as JSON.\n        \n        For Schools:\n        {\n            "type": "school",\n            "campus_type": "main|branch",\n            "campus_photo_url": "...",\n            "shift_available": "morning|afternoon|both",\n            "grades_offered": "Nursery,KG-I,1,2,3...",\n            "total_students": 450,\n            "male_students": 230,\n            "female_students": 220,\n            "total_teachers": 25,\n            "total_classrooms": 15,\n            "total_offices": 3,\n            "library_available": true,\n            "sports_available": "Cricket, Football",\n            "accreditation": "BISE Karachi",\n            "instruction_language": "English, Urdu",\n            "academic_year_start_month": "April",\n            "academic_year_end_month": "March",\n            ... (all other Campus model fields)\n        }\n        \n        For Hospitals:\n        {\n            "type": "hospital",\n            "num_beds": 100,\n            "specializations": ["Cardiology", "Neurology"],\n            "emergency_services": true\n        }\n        \n        For Kitchens:\n        {\n            "type": "kitchen",\n            "daily_capacity": 5000,\n            "meal_types": ["breakfast", "lunch", "dinner"]\n        }\n        ')),
                ('legacy_campus_id', models.IntegerField(blank=True, help_text='Link to SIS Campus.id for migration tracking', null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(help_text='Parent institution this branch belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='employees.institution')),
            ],
            options={
                'verbose_name': 'Branch',
                'verbose_name_plural': 'Branches',
                'ordering': ['branch_code'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'dept_code'), ('institution', 'dept_code')},
        ),
        migrations.AddField(
            model_name='department',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='employees.branch'),
        ),
        migrations.AddField(
            model_name='employeeassignment',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch where employee works (for branch-specific roles)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='employees.branch'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('organization', 'dept_code'), ('institution', 'dept_code'), ('branch', 'dept_code')},
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['branch_code'], name='employees_b_branch__b63613_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['legacy_campus_id'], name='employees_b_legacy__6ed2c3_idx'),
        ),
    ]
