# Generated by Django 4.2 on 2026-01-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0008_branch_alter_department_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeassignment',
            name='shift',
            field=models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('night', 'Night'), ('general', 'General/Office'), ('hourly', 'Hourly Base'), ('both', 'Both (M+A)')], default='general', max_length=20),
        ),
    ]
