# Generated by Django 4.2 on 2026-01-24 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0009_alter_employeeassignment_shift'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='employment_type',
            field=models.CharField(choices=[('full_time', 'Full-time'), ('part_time', 'Part-time'), ('contract', 'Contract'), ('intern', 'Intern')], default='full_time', max_length=20),
        ),
    ]
