# Generated by Django 5.0.1 on 2026-04-21 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_employment_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='designation',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
