# Generated by Django 5.0.1 on 2026-04-23 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0011_designation_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeassignment',
            name='institution',
        ),
    ]
