# Generated by Django 5.0.1 on 2026-04-23 13:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0012_remove_employeeassignment_institution'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='branch',
            name='employees_b_legacy__6ed2c3_idx',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='domain_data',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='legacy_campus_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='attribute_schema',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='extra_data',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='inst_id',
        ),
        migrations.RemoveField(
            model_name='institution',
            name='legacy_campus_id',
        ),
        migrations.AlterField(
            model_name='institution',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='institutions', to='employees.organization'),
        ),
    ]
