# Generated by Django 5.0.1 on 2026-04-24 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0013_institution_branch_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_superadmin',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='state',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
