# Generated by Django 5.0.1 on 2025-11-29 07:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceAccess',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('service', models.CharField(choices=[('sis', 'School Information System (SIS)'), ('hdms', 'Help Desk Management System (HDMS)'), ('finance', 'Finance Management (Future)'), ('hr', 'HR Management (Future)'), ('procurement', 'Procurement (Future)')], help_text='Which service this access is for', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Can employee currently access this service?')),
                ('granted_at', models.DateTimeField(auto_now_add=True, help_text='When access was granted')),
                ('revoked_at', models.DateTimeField(blank=True, help_text='When access was revoked (if applicable)', null=True)),
                ('notes', models.TextField(blank=True, help_text='Admin notes about this access grant', null=True)),
                ('employee', models.ForeignKey(help_text='Employee who has access', on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to='employees.employee')),
                ('granted_by', models.ForeignKey(help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='employees.employee')),
                ('revoked_by', models.ForeignKey(blank=True, help_text='Admin who revoked this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revoked_accesses', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Service Access',
                'verbose_name_plural': 'Service Accesses',
                'db_table': 'permissions_service_access',
            },
        ),
        migrations.CreateModel(
            name='HdmsRole',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role_type', models.CharField(choices=[('moderator', 'Moderator (Full ticket management)'), ('assignee', 'Assignee (Can be assigned tickets)'), ('requestor', 'Requestor (Can only create tickets)')], help_text='HDMS role type', max_length=20)),
                ('can_view_all_tickets', models.BooleanField(default=False, help_text='Can view all tickets (moderator privilege)')),
                ('can_assign_tickets', models.BooleanField(default=False, help_text='Can assign tickets to others (moderator privilege)')),
                ('can_close_tickets', models.BooleanField(default=False, help_text='Can close/resolve tickets (moderator privilege)')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, help_text='When role was assigned')),
                ('assigned_by', models.ForeignKey(help_text='Admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hdms_roles', to='employees.employee')),
                ('service_access', models.OneToOneField(help_text='HDMS service access this role is for', on_delete=django.db.models.deletion.CASCADE, related_name='hdms_role', to='permissions.serviceaccess')),
            ],
            options={
                'verbose_name': 'HDMS Role',
                'verbose_name_plural': 'HDMS Roles',
                'db_table': 'permissions_hdms_role',
            },
        ),
        migrations.CreateModel(
            name='PermissionAudit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('grant_access', 'Access Granted'), ('revoke_access', 'Access Revoked'), ('assign_role', 'Role Assigned'), ('change_role', 'Role Changed'), ('remove_role', 'Role Removed')], help_text='What action was performed', max_length=20)),
                ('service', models.CharField(help_text='Which service (SIS/HDMS)', max_length=20)),
                ('details', models.JSONField(default=dict, help_text='Additional details about the change')),
                ('performed_at', models.DateTimeField(auto_now_add=True, help_text='When action was performed')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of admin', null=True)),
                ('employee', models.ForeignKey(help_text='Employee whose permissions changed', on_delete=django.db.models.deletion.CASCADE, related_name='permission_audits', to='employees.employee')),
                ('performed_by', models.ForeignKey(help_text='Admin who performed this action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_permission_changes', to='employees.employee')),
            ],
            options={
                'verbose_name': 'Permission Audit',
                'verbose_name_plural': 'Permission Audits',
                'db_table': 'permissions_audit',
                'ordering': ['-performed_at'],
                'indexes': [models.Index(fields=['employee', '-performed_at'], name='permissions_employe_de42ba_idx'), models.Index(fields=['service', '-performed_at'], name='permissions_service_304c44_idx'), models.Index(fields=['performed_by', '-performed_at'], name='permissions_perform_144a05_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='serviceaccess',
            index=models.Index(fields=['employee', 'service', 'is_active'], name='permissions_employe_59f135_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceaccess',
            index=models.Index(fields=['service', 'is_active'], name='permissions_service_b31a55_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceaccess',
            unique_together={('employee', 'service')},
        ),
    ]
