# Generated by Django 5.0.1 on 2025-12-08 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_alter_department_dept_code_and_more'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hdmsrole',
            name='can_manage_users',
            field=models.BooleanField(default=False, help_text='Can manage HDMS users and permissions (admin privilege)'),
        ),
        migrations.AlterField(
            model_name='hdmsrole',
            name='assigned_by',
            field=models.ForeignKey(blank=True, help_text='Admin who assigned this role', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_hdms_roles', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='hdmsrole',
            name='role_type',
            field=models.CharField(choices=[('admin', 'Administrator (Full system access)'), ('moderator', 'Moderator (Full ticket management)'), ('assignee', 'Assignee (Can be assigned tickets)'), ('requestor', 'Requestor (Can only create tickets)')], help_text='HDMS role type', max_length=20),
        ),
        migrations.AlterField(
            model_name='serviceaccess',
            name='granted_by',
            field=models.ForeignKey(blank=True, help_text='Admin who granted this access', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_accesses', to='employees.employee'),
        ),
    ]
