# Generated by Django 4.2 on 2026-01-27 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_usercredentials_employee_superadmin_and_more'),
        ('employees', '0010_employee_employment_type'),
        ('permissions', '0002_add_admin_role_and_manage_users'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='serviceaccess',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='serviceaccess',
            name='superadmin',
            field=models.ForeignKey(blank=True, help_text='SuperAdmin who has access (if superadmin)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to='authentication.superadmin'),
        ),
        migrations.AlterField(
            model_name='serviceaccess',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee who has access (if employee)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='service_accesses', to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='serviceaccess',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Can user currently access this service?'),
        ),
        migrations.AddIndex(
            model_name='serviceaccess',
            index=models.Index(fields=['superadmin', 'service', 'is_active'], name='permissions_superad_b28045_idx'),
        ),
    ]
