# Generated by Django 5.0.1 on 2026-06-15 09:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0006_alter_service_id_alter_vmsrole_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codename', models.CharField(help_text="e.g. 'employee.create'", max_length=100, unique=True)),
                ('name', models.CharField(help_text="e.g. 'Create Employee'", max_length=200)),
                ('service', models.CharField(help_text='Service code this permission belongs to', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'permissions_rbac_permission',
                'ordering': ['service', 'codename'],
            },
        ),
    ]
