# Generated by Django 5.0.1 on 2026-06-15 09:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permissions', '0007_rbac_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text="e.g. 'HR Manager'", max_length=100)),
                ('service', models.CharField(help_text='Service code this role applies to', max_length=20)),
                ('is_default', models.BooleanField(default=False, help_text='Pre-seeded default role')),
                ('description', models.TextField(blank=True, default='')),
                ('permissions', models.ManyToManyField(blank=True, help_text='Permissions bundled into this role', related_name='roles', to='permissions.permission')),
            ],
            options={
                'db_table': 'permissions_rbac_role',
                'ordering': ['service', 'name'],
                'unique_together': {('name', 'service')},
            },
        ),
    ]
