# Generated by Django 5.0.1 on 2026-06-15 10:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('employees', '0018_remove_employeeassignment_branch'),
        ('permissions', '0008_rbac_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeePermissionOverride',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_allowed', models.BooleanField(help_text='True = grant extra permission. False = block permission from role.')),
                ('scope_object_id', models.UUIDField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_overrides', to='employees.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_permission_overrides', to='employees.employee')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_overrides', to='permissions.permission')),
                ('scope_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'permissions_rbac_employee_permission_override',
            },
        ),
        migrations.CreateModel(
            name='EmployeeRole',
            fields=[
                ('is_deleted', models.BooleanField(db_index=True, default=False, help_text='Indicates if this record is soft-deleted')),
                ('deleted_at', models.DateTimeField(blank=True, help_text='Timestamp when record was deleted', null=True)),
                ('deleted_by', models.UUIDField(blank=True, help_text='UUID of employee who deleted this record', null=True)),
                ('deletion_reason', models.TextField(blank=True, help_text='Optional reason for deletion', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when record was created')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Timestamp when record was last updated')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope_object_id', models.UUIDField(blank=True, null=True)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='employees.employee')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_employee_roles', to='employees.employee')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_roles', to='permissions.role')),
                ('scope_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'permissions_rbac_employee_role',
            },
        ),
    ]
