# Generated by Django 4.2 on 2026-01-29 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0010_employee_employment_type'),
        ('authentication', '0002_alter_usercredentials_employee_superadmin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='superadmin',
            field=models.ForeignKey(blank=True, help_text='SuperAdmin this token belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='authentication.superadmin'),
        ),
        migrations.AlterField(
            model_name='refreshtoken',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Employee this token belongs to', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='refresh_tokens', to='employees.employee'),
        ),
    ]
