name: Deploy Auth-Service

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Configure git auth
        run: |
          git config --global url."https://x-access-token:${{ github.token }}@github.com/".insteadOf "https://github.com/"

      - name: Deploy
        run: |
          cd /var/www/erp_new/Auth-service
          git pull origin main
          docker compose build --no-cache
          docker compose up -d
          docker exec -u root auth_service python manage.py collectstatic --noinput || true
          echo "Auth-service deployed successfully"
